package com.hc.mall.mapper;

import com.hc.mall.model.PmsProductOperateLog;
import com.hc.mall.model.PmsProductOperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    long countByExample(PmsProductOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int deleteByExample(PmsProductOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int insert(PmsProductOperateLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int insertSelective(PmsProductOperateLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    List<PmsProductOperateLog> selectByExample(PmsProductOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    PmsProductOperateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int updateByExampleSelective(@Param("row") PmsProductOperateLog row, @Param("example") PmsProductOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int updateByExample(@Param("row") PmsProductOperateLog row, @Param("example") PmsProductOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int updateByPrimaryKeySelective(PmsProductOperateLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_operate_log
     *
     * @mbg.generated Sat Oct 26 17:42:57 CST 2024
     */
    int updateByPrimaryKey(PmsProductOperateLog row);
}