services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 4306:3306
    volumes:
      - ./mydata/mysql/data/db:/var/lib/mysql #数据文件挂载
      - ./mydata/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - ./mydata/mysql/log:/var/log/mysql #日志文件挂载

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - ./mydata/redis/data:/data #数据文件挂载
    ports:
      - 7379:6379